---
- name: "Create ec2 instance"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Provision a test instance"
      ec2:
         aws_access_key: "{{ lookup('env', 'AWSAccessKeyId') }}"
         aws_secret_key: "{{ lookup('env', 'AWSSecretKey') }}"
         instance_type: t2.micro
         image: "ami-0998bf58313ab53da"
         wait: true
         region: "us-east-2"
         instance_tags:
            type: "test"
         count_tag:
            type: "test"
         exact_count: 1
